//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Vision
{
    [Serializable]
    public class Detection2DMsg : Message
    {
        public const string k_RosMessageName = "vision_msgs/Detection2D";
        public override string RosMessageName => k_RosMessageName;

        //  Defines a 2D detection result.
        public Std.HeaderMsg header;
        //  Class probabilities
        public ObjectHypothesisWithPoseMsg[] results;
        //  2D bounding box surrounding the object.
        public BoundingBox2DMsg bbox;
        //  ID used for consistency across multiple detection messages.
        public string id;

        public Detection2DMsg()
        {
            this.header = new Std.HeaderMsg();
            this.results = new ObjectHypothesisWithPoseMsg[0];
            this.bbox = new BoundingBox2DMsg();
            this.id = "";
        }

        public Detection2DMsg(Std.HeaderMsg header, ObjectHypothesisWithPoseMsg[] results, BoundingBox2DMsg bbox, string id)
        {
            this.header = header;
            this.results = results;
            this.bbox = bbox;
            this.id = id;
        }

        public static Detection2DMsg Deserialize(MessageDeserializer deserializer) => new Detection2DMsg(deserializer);

        private Detection2DMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.results, ObjectHypothesisWithPoseMsg.Deserialize, deserializer.ReadLength());
            this.bbox = BoundingBox2DMsg.Deserialize(deserializer);
            deserializer.Read(out this.id);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.results);
            serializer.Write(this.results);
            serializer.Write(this.bbox);
            serializer.Write(this.id);
        }

        public override string ToString()
        {
            return "Detection2DMsg: " +
            "\nheader: " + header.ToString() +
            "\nresults: " + System.String.Join(", ", results.ToList()) +
            "\nbbox: " + bbox.ToString() +
            "\nid: " + id.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
