//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Vision
{
    [Serializable]
    public class ObjectHypothesisWithPoseMsg : Message
    {
        public const string k_RosMessageName = "vision_msgs/ObjectHypothesisWithPose";
        public override string RosMessageName => k_RosMessageName;

        //  An object hypothesis that contains pose information.
        public ObjectHypothesisMsg hypothesis;
        //  The 6D pose of the object hypothesis.
        public Geometry.PoseWithCovarianceMsg pose;

        public ObjectHypothesisWithPoseMsg()
        {
            this.hypothesis = new ObjectHypothesisMsg();
            this.pose = new Geometry.PoseWithCovarianceMsg();
        }

        public ObjectHypothesisWithPoseMsg(ObjectHypothesisMsg hypothesis, Geometry.PoseWithCovarianceMsg pose)
        {
            this.hypothesis = hypothesis;
            this.pose = pose;
        }

        public static ObjectHypothesisWithPoseMsg Deserialize(MessageDeserializer deserializer) => new ObjectHypothesisWithPoseMsg(deserializer);

        private ObjectHypothesisWithPoseMsg(MessageDeserializer deserializer)
        {
            this.hypothesis = ObjectHypothesisMsg.Deserialize(deserializer);
            this.pose = Geometry.PoseWithCovarianceMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.hypothesis);
            serializer.Write(this.pose);
        }

        public override string ToString()
        {
            return "ObjectHypothesisWithPoseMsg: " +
            "\nhypothesis: " + hypothesis.ToString() +
            "\npose: " + pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
