//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Vision
{
    [Serializable]
    public class ObjectHypothesisMsg : Message
    {
        public const string k_RosMessageName = "vision_msgs/ObjectHypothesis";
        public override string RosMessageName => k_RosMessageName;

        //  The unique ID of the object class.
        public string class_id;
        //  The probability or confidence value of the detected object.
        public double score;

        public ObjectHypothesisMsg()
        {
            this.class_id = "";
            this.score = 0.0;
        }

        public ObjectHypothesisMsg(string class_id, double score)
        {
            this.class_id = class_id;
            this.score = score;
        }

        public static ObjectHypothesisMsg Deserialize(MessageDeserializer deserializer) => new ObjectHypothesisMsg(deserializer);

        private ObjectHypothesisMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.class_id);
            deserializer.Read(out this.score);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.class_id);
            serializer.Write(this.score);
        }

        public override string ToString()
        {
            return "ObjectHypothesisMsg: " +
            "\nclass_id: " + class_id.ToString() +
            "\nscore: " + score.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
