//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Vision
{
    [Serializable]
    public class Pose2DMsg : Message
    {
        public const string k_RosMessageName = "vision_msgs/Pose2D";
        public override string RosMessageName => k_RosMessageName;

        public Point2DMsg position;
        public double theta;

        public Pose2DMsg()
        {
            this.position = new Point2DMsg();
            this.theta = 0.0;
        }

        public Pose2DMsg(Point2DMsg position, double theta)
        {
            this.position = position;
            this.theta = theta;
        }

        public static Pose2DMsg Deserialize(MessageDeserializer deserializer) => new Pose2DMsg(deserializer);

        private Pose2DMsg(MessageDeserializer deserializer)
        {
            this.position = Point2DMsg.Deserialize(deserializer);
            deserializer.Read(out this.theta);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.position);
            serializer.Write(this.theta);
        }

        public override string ToString()
        {
            return "Pose2DMsg: " +
            "\nposition: " + position.ToString() +
            "\ntheta: " + theta.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
